-- User: social
CREATE USER social WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

COMMENT ON ROLE social IS 'Social owner';

ALTER DATABASE "SocialDB" OWNER TO social;